# Generated by Django 6.0.4 on 2026-04-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_professional_user_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendado'), ('confirmed', 'Confirmado'), ('pending', 'Pendente'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='scheduled', max_length=20),
        ),
    ]
