# Generated by Django 6.0.4 on 2026-04-09 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_external_enabled', models.BooleanField(default=True)),
                ('webhook_enabled', models.BooleanField(default=False)),
                ('webhook_url', models.URLField(blank=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=255)),
                ('webhook_events', models.JSONField(blank=True, default=list)),
                ('google_calendar_enabled', models.BooleanField(default=False)),
                ('google_calendar_id', models.CharField(blank=True, max_length=255)),
                ('google_calendar_sync_mode', models.CharField(default='read_write', max_length=20)),
                ('google_meet_enabled', models.BooleanField(default=False)),
                ('google_meet_auto_create', models.BooleanField(default=True)),
                ('google_meet_organizer_email', models.EmailField(blank=True, max_length=254)),
                ('mcp_enabled', models.BooleanField(default=False)),
                ('mcp_provider', models.CharField(blank=True, max_length=100)),
                ('mcp_assistant_name', models.CharField(blank=True, max_length=255)),
                ('mcp_endpoint', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integration_settings', to='core.clinic')),
            ],
        ),
    ]
